=== captechconsulting/alfred/src/test/resources/hierarchical/sample-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2018 CapTech Ventures, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.captechconsulting.com/sample-schema"
	xmlns:tns="http://www.captechconsulting.com/sample-schema" elementFormDefault="qualified">

    <element name="meter">
    	<annotation>
    		<documentation>Represents a meter with its readings over time.</documentation>
    	</annotation>
    	<complexType>
    		<sequence>
    			<element name="readings" type="tns:meter-readings" minOccurs="1" maxOccurs="1">
    				<annotation>
    					<documentation>a set of meter readings</documentation>
    				</annotation>
    			</element>
    			<element name="documentation" type="string"/>
    		</sequence>
    		<attribute name="number" type="string" use="required"/>
    		<attribute name="address" type="string" use="required"/>
    	</complexType>
    </element>

    <complexType name="meter-readings">
    	<sequence>
    		<element name="reading" minOccurs="0" maxOccurs="unbounded">
    			<annotation>
    				<documentation>represents a reading at a point in time</documentation>
    			</annotation>
    			<complexType>
    				<attribute name="timestamp" type="string" use="required">
    					<annotation>
    						<documentation>time of the reading</documentation>
    					</annotation>
    				</attribute>
    				<attribute name="value" type="decimal">
    					<annotation>
    						<documentation>value of the reading</documentation>
    					</annotation>
    				</attribute>
    			</complexType>
    		</element>
    	</sequence>
    </complexType>
</schema>

=== captechconsulting/alfred/src/test/resources/hierarchical/sample-schema-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2018 CapTech Ventures, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<tns:meter address="meter address" number="meter number" xmlns:tns="http://www.captechconsulting.com/sample-schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.captechconsulting.com/sample-schema sample-schema.xsd ">
  <tns:readings>
    <tns:reading timestamp="2017-06-01T12:30:04-04:00" value="1.0"/>
    <tns:reading timestamp="2017-06-01T13:00:05-04:00" value="2.0"/>
    <tns:reading timestamp="2017-06-01T13:30:06-04:00" value="3.0"/>
    <tns:reading timestamp="2017-06-01T14:00:07-04:00" value="4.0"/>
    <tns:reading timestamp="2017-06-01T14:30:08-04:00" value="5.0"/>
  </tns:readings>
  <tns:documentation>Here's some documentation text</tns:documentation>
</tns:meter>
